[package]
name = "opus-daemon"
version = "0.1.0"
authors = ["Sean Behan <codebam@riseup.net>"]
edition = "2018"

[dependencies]
structopt = "0.2.18"
config = "0.9.3"
lazy_static = "1.3.0"
notify = { version = "=5.0.0-pre.1", features = ["serde"] }
crossbeam-channel = "0.3.8"
